version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: messenger-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - messenger-network

  grafana:
    image: grafana/grafana:latest
    container_name: messenger-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - messenger-network

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  messenger-network:
    external: true
