version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: messenger-app
        container_name: messenger-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/nginx/default.conf:/etc/nginx/http.d/default.conf
            - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
        ports:
            - "8000:8000"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=messenger
            - DB_USERNAME=messenger
            - DB_PASSWORD=messenger
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks:
            - messenger-network
        depends_on:
            - db
            - redis

    db:
        image: postgres:15-alpine
        container_name: messenger-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: messenger
            POSTGRES_USER: messenger
            POSTGRES_PASSWORD: messenger
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/postgresql/conf:/etc/postgresql
        ports:
            - "5432:5432"
        networks:
            - messenger-network

    redis:
        image: redis:7-alpine
        container_name: messenger-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - messenger-network

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local

networks:
    messenger-network:
        driver: bridge
