version: '3.8'

services:
    qms-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: heruvim6w/qms-api
        container_name: qms-api
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/nginx/default.conf:/etc/nginx/http.d/default.conf
            - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
        ports:
            - "8000:8000"
        environment:
            - APP_NAME=QMS API
            - DB_HOST=qms-db
            - DB_DATABASE=qms_db
            - DB_USERNAME=qms_user
            - DB_PASSWORD=qms_password
            - REDIS_HOST=qms-redis
        networks:
            - qms-network
        depends_on:
            - qms-db
            - qms-redis

    qms-db:
        image: postgres:15-alpine
        container_name: qms-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: qms_db
            POSTGRES_USER: qms_user
            POSTGRES_PASSWORD: qms_password
        ports:
            - "5432:5432"
        volumes:
            - qms_postgres_data:/var/lib/postgresql/data
        networks:
            - qms-network

    qms-redis:
        image: redis:7-alpine
        container_name: qms-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - qms_redis_data:/data
        networks:
            - qms-network

volumes:
    qms_postgres_data:
        driver: local
    qms_redis_data:
        driver: local

networks:
    qms-network:
        driver: bridge
